# Generated by Django 5.2.9 on 2025-12-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pidx',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
