# Generated by Django 5.2.9 on 2025-12-25 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_deliveryperson_approved_at_deliveryperson_is_active_and_more'),
        ('store', '0005_payment_purchase_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.deliveryperson'),
        ),
    ]
