# Generated by Django 5.2.9 on 2025-12-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_delivery_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('on_the_way', 'On the way'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
