# Generated by Django 5.2.9 on 2025-12-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.TextField(choices=[('delivery_person', 'Delivery Person'), ('admin', 'Admin'), ('customer', 'Customer')], default='customer'),
        ),
    ]
