# Generated by Django 5.2.9 on 2025-12-24 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(help_text='Date of Birth')),
                ('phone_number', models.CharField(help_text='Phone Number', max_length=10)),
                ('emergency_contact', models.CharField(help_text='Contact Number for Emergency cases', max_length=10)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('citizenship', models.FileField(blank=True, help_text='front and back side of citizenship card in pdf format', null=True, upload_to='deliver_person/citizenships/')),
                ('driving_license', models.FileField(blank=True, help_text='Clear scanned image of driving license', null=True, upload_to='deliver_person/driving_licenses/')),
                ('vehicle_type', models.CharField(choices=[('bicycle', 'Bicycle'), ('motorcycle', 'Motorcycle'), ('car', 'Car'), ('van', 'Van'), ('truck', 'Truck')], max_length=100)),
                ('vehicle_plate_number', models.CharField(max_length=10)),
                ('vehicle_color', models.ImageField(blank=True, default='black', help_text='Color of vehicle', null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
