# Generated by Django 5.2.9 on 2025-12-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_deliveryperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryperson',
            name='vehicle_color',
            field=models.CharField(blank=True, default='black', help_text='Color of vehicle', max_length=100, null=True),
        ),
    ]
